# Generated by Django 2.2.6 on 2021-01-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='productID',
            new_name='listingid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
